#主配置文件
spring:
  application:
    name: fasaxi-emma
  # 激活环境配置
  profiles:
    active: local
  # 文件编码 UTF8
  mandatory-file-encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    hikari:
      initialization-fail-timeout: 10000  # 启动时连接超时时间（毫秒）
      minimum-idle: 5                    # 最小空闲连接数
      maximum-pool-size: 10              # 最大连接数
      max-lifetime: 3500000
      connection-timeout: 5000          # 连接超时时间
      validation-timeout: 5000           # 连接验证超时时间
      idle-timeout: 600000               # 空闲连接超时时间
  threads:
    virtual:
      enabled: true

server:
  # 服务端口
  port: 8802

mybatis-flex:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true


emby:
  common-ua: "AceCandy/1.0"
  item-info-url: /Items
  playback-url: /Items/{}/PlaybackInfo
  episodes-url: /emby/Shows/{}/Episodes
  remote-images-url: /Items/{}/RemoteImages
  refresh-url: /emby/Items/{}/Refresh
  cache-path: tmp/cache

tmdb:
  host: http://api.tmdb.org
  api-key: 950257e1e6e1b7e0daf665312d82e922
  detail-info-url: /3/{}/{}
  image-info-url: /3/tv/1399/images
  image-static-url: https://image.tmdb.org/t/p/original
  image-cdn-url:
    - http://pic.acecandy.cn/t/p/w{}
    - http://pic1.acecandy.cn/t/p/w{}
    - http://pic.worldline.space/t/p/w{}
    - http://static-mdb.v.geilijiasu.com/t/p/w{}

douban:
  image-static-url: https://img2.doubanio.com
  image-cdn-url: http://pic.worldline.space
  app:
    host: https://api.douban.com
    apikey:
      - 0ab215a8b1977939201640fa14c66bab
  wxmini:
    host: https://frodo.douban.com
    apikey:
      - 0ac44ae016490db2204ce0a042db2916
      - 054022eaeae0b00e0fc068c0c0a2102a
    detail-info-url: /api/v2/{}/{}